name: knn_best_worst_seed
id: knn_best_worst_seed
description: Collecting 5 smallest eigenvalue gaps and corresponding PCs, according subspace errors and seeds that correspond to the best/worst subspace error at a given PC
benchmarker: "Diana Stepushkina <stepushkina.05@gmail.com>"
version: "0.1.0"

software_backend: "conda"

software_environments:
  scanpy_env:
    name: Scanpy environment
    conda: envs/scanpy.yaml

stages:

  - id: KNN_INPUT
    outputs:
      - id: selected_seeds
        path: "selected_seeds.tsv"
      - id: pca_manifest
        path: "pca_manifest.tsv"

    modules:
      - id: local_knn_inputs
        name: "Existing principal-angle outputs"
        software_environment: scanpy_env
        repository:
          url: /Users/dianastepushkina/Desktop/randomized_benchmark/Randomized_PCA
          commit: 3abdcebadcce5f95692439a669140106da4f32fd
          entrypoint: knn-inputs
        parameters:
          - selected_seeds_source: "principal_angles/selected_seeds.tsv"
            pca_manifest_source: "principal_angles/pca_manifest.tsv"

  - id: KNN
    inputs:
      - selected_seeds
      - pca_manifest

    outputs:
      - id: selected_knn_manifest
        path: "{dataset}_selected_knn_manifest.tsv"

    modules:
      - id: selected_knn
        name: "Selected exact/best/worst kNN graphs"
        software_environment: scanpy_env
        repository:
          url: /Users/dianastepushkina/Desktop/randomized_benchmark/Randomized_PCA
          commit: 3abdcebadcce5f95692439a669140106da4f32fd
          entrypoint: knn
        parameters:
          - n_neighbors: 15
            flavor: umap
            random_seed: 1
  - id: KNN_OVERLAP
    inputs:
      - selected_knn_manifest
    outputs:
      - id: knn_overlap
        path: "{dataset}_knn_overlap.tsv"

    modules:
      - id: knn_overlap
        name: "kNN overlap with exact PCA"
        software_environment: scanpy_env
        repository:
          url: /Users/dianastepushkina/Desktop/randomized_benchmark/Randomized_PCA
          commit: 3abdcebadcce5f95692439a669140106da4f32fd
          entrypoint: knn-overlap

  - id: CLUSTERING
    inputs:
      - selected_knn_manifest

    outputs:
      - id: selected_clustering_manifest
        path: "{dataset}_selected_clustering_manifest.tsv"

    modules:
      - id: selected_clustering
        name: "Leiden clustering of selected kNN graphs"
        software_environment: scanpy_env
        repository:
          url: /Users/dianastepushkina/Desktop/randomized_benchmark/Randomized_PCA
          commit: 616670867f361c61982579356191d940c2039636
          entrypoint: selected-clustering
        parameters:
          - resolution: 1.0
            random_seed: 1
            flavor: igraph
            partition_type: RBConfiguration

  - id: CLUSTERING_ARI
    inputs:
      - selected_clustering_manifest
    outputs:
      - id: clustering_ari
        path: "{dataset}_clustering_ari.tsv"
    modules:
      - id: clustering_ari
        name: "Clustering ARI"
        software_environment: scanpy_env
        repository:
          url: /Users/dianastepushkina/Desktop/randomized_benchmark/Randomized_PCA
          commit: 48a8236122b30501184bdb8ad8ff815137cb62d9
          entrypoint: clustering-ari