name: randomized-pca
id: randomized_pca
description: Benchmarking randomized PCA stability and downstream effects in single-cell RNA-seq analysis
benchmarker: "Diana Stepushkina <stepushkina.05@gmail.com>"

# Benchmark configuration
version: "0.1.0"

# The default software environment for this benchmark.
# One of: apptainer, conda, envmodules.
software_backend: "conda"

# Available software environments

software_environments:
  scanpy_env:
    name: Scanpy environment
    description: Environment for Scanpy preprocessing and PCA
    conda: envs/scanpy.yaml

  scrapper_env:
    name: Scrapper environment
    description: Environment for Scrapper PCA
    conda: envs/scrapper.yaml

entrypoints:
  data: raw_h5ad.py
  normalize: normalize.py
  feat-select: feat-select.py
  pca: pca.py
  
# Stages and modules for your benchmark

stages:
  - id: DATA
    outputs:
      - id: rawdata_h5ad
        path: "{name}.h5ad"
      - id: properties_info
        path: "{name}_properties.yaml"

    modules:
      - id: p31_s42_narrow_signal
        name: "p31 s42 narrow signal"
        software_environment: scrapper_env
        repository:
          url: https://github.com/stepushkina05-jpg/randomized-pca-data.git
          commit: a84f4d04ffdfbb597cedee4d4c99f0d19951620a
          entrypoint: default
        parameters:
          - dataset_name: p31_s42_narrow_signal
      - id: p35_s42_broad_signal
        name: "p35 s42 broad signal"
        software_environment: scrapper_env
        repository:
          url: https://github.com/stepushkina05-jpg/randomized-pca-data.git
          commit: a84f4d04ffdfbb597cedee4d4c99f0d19951620a
          entrypoint: default
        parameters:
          - dataset_name: p35_s42_broad_signal
      - id: p38_s42_strong_signal
        name: "p38 s42 strong signal"
        software_environment: scrapper_env
        repository:
          url: https://github.com/stepushkina05-jpg/randomized-pca-data.git
          commit: a84f4d04ffdfbb597cedee4d4c99f0d19951620a
          entrypoint: default
        parameters:
          - dataset_name: p38_s42_strong_signal
  
  - id: IDS
    inputs:
      - rawdata_h5ad
    outputs:
      - id: filtered_cellids
        path: "{dataset}_cellids.txt.gz"
      - id: filtered_featureids
        path: "{dataset}_featureids.txt.gz"

    modules:
      - id: identity_ids
        name: "Keep all cells and genes"
        software_environment: scanpy_env
        repository:
          url: https://github.com/stepushkina05-jpg/scanpy_random
          commit: 6550c68d86810bcbc5859caf5f8aad32bac242d0
          entrypoint: ids
  
  - id: NORM
    inputs:
      - rawdata_h5ad
      - filtered_cellids
      - filtered_featureids
    outputs:
      - id: normalized_h5
        path: "{dataset}_normalized.h5"
    modules:
      - id: norm_scanpy
        name: "Scanpy CP10k log1p normalization"
        software_environment: scanpy_env
        repository:
          url: https://github.com/stepushkina05-jpg/scanpy_random
          commit: 6550c68d86810bcbc5859caf5f8aad32bac242d0
          entrypoint: normalize
        parameters:
          - flavor: log1pCP10k

  - id: FEAT
    inputs:
      - rawdata_h5ad
      - normalized_h5
      - filtered_cellids
      - filtered_featureids
      - properties_info
    outputs:
      - id: normalized_selected_h5
        path: "{dataset}_normalized_selected.h5"
    modules:
      - id: feat_scanpy
        name: "Scanpy Seurat HVG selection"
        software_environment: scanpy_env
        repository:
          url: https://github.com/omni-scrna/scanpy
          commit: 2a56c14
          entrypoint: feat-select
        parameters:
          - flavor: scanpy_seurat
            number_selected: 2000

  - id: PCA
    inputs:
      - normalized_selected_h5
    outputs:
      - id: pca_scores
        path: "{dataset}_pcas.tsv"
      - id: pca_loadings
        path: "{dataset}_loadings.tsv"

    modules:
    - id: scanpy_exact
      name: "Scanpy exact PCA"
      software_environment: scanpy_env
      repository:
        url: https://github.com/stepushkina05-jpg/scanpy_random
        commit: 6550c68d86810bcbc5859caf5f8aad32bac242d0
        entrypoint: pca
      parameters:
        - solver: full
          dense: "true"
          dtype: float64
          blas_threads: 1
          n_components: 50
          random_seed: 1
          n_iter: 2
          n_oversamples: 10

    - id: scanpy_random
      name: "Scanpy randomized PCA"
      software_environment: scanpy_env
      repository:
        url: https://github.com/stepushkina05-jpg/scanpy_random
        commit: 6550c68d86810bcbc5859caf5f8aad32bac242d0
        entrypoint: pca
      parameters:
        - &scanpy_random_base
          solver: randomized
          dense: "true"
          dtype: float64
          blas_threads: 1
          n_components: 50
          random_seed: 1
          n_iter: 2
          n_oversamples: 10

        - <<: *scanpy_random_base
          random_seed: 2

        - <<: *scanpy_random_base
          random_seed: 3

        - <<: *scanpy_random_base
          random_seed: 4

        - <<: *scanpy_random_base
          random_seed: 5

        - <<: *scanpy_random_base
          random_seed: 6

        - <<: *scanpy_random_base
          random_seed: 7

        - <<: *scanpy_random_base
          random_seed: 8

        - <<: *scanpy_random_base
          random_seed: 9

        - <<: *scanpy_random_base
          random_seed: 10
          
    - id: scrapper_random
      name: "Scrapper randomized PCA"
      software_environment: scrapper_env
      repository:
        url: https://github.com/stepushkina05-jpg/scrapper_random
        commit: 51a6fcadf67421ee3ff4dc6277cb0145d834aa8b
        entrypoint: pca
      parameters:
        - solver: random
          n_components: 50
          n_iter: 2
          n_oversamples: 10
          random_seed: 1
          num_threads: 1
    - id: scrapper_exact
      name: "Scrapper exact PCA"
      software_environment: scrapper_env
      repository:
        url: https://github.com/stepushkina05-jpg/scrapper_random
        commit: 51a6fcadf67421ee3ff4dc6277cb0145d834aa8b
        entrypoint: pca
      parameters:
        - solver: exact
          n_components: 50
          n_iter: 2
          n_oversamples: 10
          random_seed: 1
          num_threads: 1

  - id: EIGENGAP
    inputs:
      - pca_scores
    outputs:
      - id: eigengaps
        path: "{dataset}_eigengaps.tsv"
      - id: selected_k
        path: "{dataset}_smallest_eigengaps.tsv"
      - id: eigengap_figure
        path: "{dataset}_eigengaps.png"
    modules:
      - id: eigengap
        name: "Exact PCA eigengap analysis"
        software_environment: scanpy_env
        exclude:
        - scanpy_random
        - scrapper_random
        repository: 
          url: /Users/dianastepushkina/Desktop/randomized_benchmark/Randomized_PCA
          commit: 95c6a1f5b6fa29fa72299dcd00b1f63a3bd27a8b
          entrypoint: eigengap 
        parameters: 
          - n_smallest: 5 

metric_collectors:
  - id: principal_angles
    name: "PCA principal-angle subspace analysis"
    software_environment: scanpy_env
    repository:
      url: /Users/dianastepushkina/Desktop/randomized_benchmark/Randomized_PCA
      commit: 5024f885a5cbf06fb5ce6e3df3ace63d3be64734
      entrypoint: principal_angles
    inputs:
      - pca_loadings
      - selected_k
    outputs:
      - id: subspace_errors
        path: "{name}/subspace_errors.tsv"
      - id: selected_seeds
        path: "{name}/selected_seeds.tsv"
      - id: pca_manifest
        path: "{name}/pca_manifest.tsv"

  
  - id: pca_accuracy
    name: "PCA approximation accuracy"
    software_environment: scanpy_env
    repository:
      url: /Users/dianastepushkina/Desktop/randomized_benchmark/Randomized_PCA
      commit: 066581ec753b31161fa23f5a1d56fd2cb0064d52
      entrypoint: pca-accuracy
    inputs:
      - pca_loadings
      - normalized_selected_h5
    outputs:
      - id: approximation_accuracy
        path: "{name}/approximation_accuracy.tsv"
      - id: pc_correlations
        path: "{name}/pc_correlations.tsv"
      