name: randomized-pca
id: randomized_pca
description: Benchmarking randomized PCA stability and downstream effects in single-cell RNA-seq analysis
benchmarker: "Diana Stepushkina <stepushkina.05@gmail.com>"

# Benchmark configuration
version: "0.1.0"

# The default software environment for this benchmark.
# One of: apptainer, conda, envmodules.
software_backend: "conda"

# Available software environments

software_environments:
    conda_env:
        name: nicely packaged environment
        description: A more verbose description, for humans reading this
        conda: envs/conda.yaml

entrypoints:
  ids: ids.py
  normalize: normalize.py
  feat-select: feat-select.py
  pca: pca.py
  
# Stages and modules for your benchmark

stages:
  - id: DATA
    outputs:
      - id: rawdata_h5ad
        path: "local_data.h5ad"
    modules:
      - id: local_data
        name: "Local H5AD input"
        software_environment: conda_env
        repository:
          url: /Users/dianastepushkina/Desktop/randomized_benchmark/Randomized_PCA
          commit: main
          entrypoint: data
  
  - id: IDS
    inputs:
      - rawdata_h5ad
    outputs:
      - id: filtered_cellids
        path: "{name}_cellids.txt.gz"
      - id: filtered_featureids
        path: "{name}_featureids.txt.gz"

    modules:
      - id: identity_ids
        name: "Keep all cells and genes"
        software_environment: conda_env
        repository:
          url: /Users/dianastepushkina/Desktop/randomized_benchmark/scanpy_random
          commit: 99eef635f178a1bc6ca78adb6e1287f159b817b3
          entrypoint: ids
  
